# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c9ba3eef78b23dd7472243bbdc8022b"
name = "print-frams"
application_url = "https://print-frame-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "v2sotre.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"


  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/update"


  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks/orders/shipment"


  [[webhooks.subscriptions]]
  topics = [ "fulfillments/update" ]
  uri = "/webhooks/orders/shipment"


  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders/cancel"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_fulfillments,write_fulfillments, read_customers "

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
[app_proxy]
url = "https://print-frame-app.onrender.com/"
prefix = "apps"
subpath = "upload-url"


[pos]
embedded = false
